### ISSUE TITLE
Client doesn't work for GetAll with custom GetAllResponseWrapper

### ISSUE THREAD

**Issue by calvinmclean** [calvinmclean/babyapi#15]
If an API uses `GetAllResponseWrapper` to return a custom response type, the included `Client` no longer correctly decodes the response. The easy fix is to require configuring the `Client` with the correct type, but ideally there is an option that can be done automatically, either using the `ResponseWrapper` function, or refactoring the feature to use a different implementation of custom responses that already works on the client side.

**Comment by calvinmclean** [comment]
Hi @blinkeye! Thank you for the feedback and for being a user of `babyapi`!

I figured out a better way to handle HTML template wrappers after creating this example, so #59 updates it to be compatible with the `Client` by default. I'll hopefully get around to fixing the underlying issue soon, but this should help make the example more usable in the meantime.

Thanks again!

**Comment by blinkeye** [comment]
Excellent, I can confirm the example is now working with the CLI as well. Much appreciated!

**Comment by calvinmclean** [comment]
Merged #60 and released `v0.11.0` which fixes this issue. This updates the CLI to use more generic request methods from the `Client` since the CLI just needs to print the output and doesn't care about types.
